# Generated by Django 5.1.1 on 2024-10-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_user_email_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
