# Generated by Django 5.1.1 on 2024-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователь'},
        ),
    ]
