# Generated by Django 5.1.1 on 2024-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=2, null=True),
        ),
    ]
