# Generated by Django 5.1.1 on 2024-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='height_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
