# Generated by Django 5.1.1 on 2024-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_alter_task_height_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('op', 'Open'), ('cl', 'Close'), ('pr', 'Process')], max_length=2, null=True),
        ),
    ]
