# Generated by Django 5.1.1 on 2024-10-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0007_alter_comment_task_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachment',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
