# Generated by Django 5.1.1 on 2024-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0014_alter_comment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='specs',
            field=models.FileField(blank=True, null=True, upload_to='Downloads', verbose_name='файл'),
        ),
    ]
