# Generated by Django 5.1.1 on 2024-10-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0015_alter_comment_specs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
